[package]
name = "protoflight"
version = "0.1.2"
edition = "2024"
resolver = "2" # <-- FORCE THIS TO STOP BUILD-DEPENDENCY BLEEDING
authors = ["Martin Budden"]
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/martinbudden/crate-protoflight"
description = "Protoflight flight controller."
keywords = ["flight", "no-std"]
categories = [
    "embedded",
    "mathematics",
    "no-std",
    "science::robotics",
    "aerospace::drones",
]

[package.metadata.docs.rs]
all-features = true

[build-dependencies]
rustc_version = "0.4.1"

[features]
#default = ["std", "libm"]
#default = ["rp2350", "libm"]
default = ["libm",
    "std",
    #"rp2350",
    #"speedybee_f405_v4",
    #"sp_racing_f4_evo",
    #"airb_omnibus_f4",
    #"matek_f405_wte",
    #"rpi_pico2",
    #"madflight_fc3", # rp235xb board
    "autopilot",
    "barometer",
    "battery",
    "blackbox",
    "debug",
    "dshot_telemetry",
    #"eight_motors",
    "gps",
    "huffman",
    "magnetometer",
    #"max7456", # this doesn't compile yet
    "msp",
    "optical_flow",
    "osd",
    "rangefinder",
    "rpm_filters",
    "rtt-debug",
    "servos",
    #"serde",
    "vtx",
]
#default = ["rp2350", "libm", "blackbox", "max7456", "osd", "rpm_filters", "barometer", "gps", "msp", "autopilot", "rangefinder"]
#default = ["rp2350", "libm", "max7456", "osd"]
#default = ["std", "libm", "blackbox", "rpm_filters", "barometer", "msp", "autopilot"]
#default = ["rp2350", "blackbox", "libm", "osd"]

autopilot = []
barometer = ["blackbox-logger/barometer"]
battery = []
blackbox = ["dep:blackbox-logger", "dep:embedded-sdmmc"]
cms = []
dashboard = []
debug = ["blackbox-logger/debug"]
dshot_telemetry = ["blackbox-logger/dshot_telemetry"]
eight_motors = ["blackbox-logger/eight_motors", "motor-mixers/eight_motors"]
gps = ["blackbox-logger/gps"]
huffman = ["blackbox-logger/huffman"]
magnetometer = ["blackbox-logger/magnetometer"]
max7456 = []
msp = []
optical_flow = []
osd = []
osd_hd = []
rangefinder = ["blackbox-logger/rangefinder"]
rpm_filters = []
servos = ["blackbox-logger/servos"]
vtx = []
# embassy executors
multicore = []
realtime_executor = []
# stm32 motor timers
motors_t8 = [ "motor-mixers/motors_t8"]
motors_t4_t3 = [ "motor-mixers/motors_t4_t3"]
motors_t3_t2 = [ "motor-mixers/motors_t3_t2"]


# Boards supported
rpi_pico2 = ["rp2350", "rp235xa"] #, "multicore"]
madflight_fc3 = ["rp2350", "rp235xb"] #, "multicore"]
matek_f405_wte = ["stm32", "stm32f405", "motors_t4_t3"]
speedybee_f405_v4 = ["stm32", "stm32f405", "motors_t4_t3", "realtime_executor"]
sp_racing_f4_evo = ["stm32", "stm32f405", "motors_t8"]
airb_omnibus_f4 = ["stm32", "stm32f405", "motors_t8"]
airb_omnibus_f4_sd = ["stm32", "stm32f405", "motors_t3_t2"]

# Core backend features declared explicitly
# libm feature activates the optional crate named "libm", etc
libm = ["dep:libm", "num-traits/libm", "vqm/libm", "imu-sensors/libm", "signal-filters/libm", "radio-controllers/libm"]
serde = ["dep:serde", "blackbox-logger/serde", "imu-sensors/serde", "motor-mixers/serde", "radio-controllers/serde", "simple-bitset/serde", "vqm/serde" ]
rtt-debug = ["dep:rtt-target"]
# align feature activates align feature in vqm and signal-filters crates, etc
align = ["vqm/align", "signal-filters/align"]
simd = ["vqm/simd", "signal-filters/simd"]
#sequential-storage = ["dep:sequential-storage"]

# Target platforms
std = [
    "critical-section/std",
    "derive_more/std",
    "embassy-time/std",
    "embassy-executor/platform-std",
    "imu-sensors/std",
    "num-traits/std",
    "motor-mixers/std",
    "signal-filters/std",
    "vqm/std",
    "log/std",
    "dep:embedded-storage-file",
    # Activate the desktop logger tools ONLY on the standard library platform
    "dep:env_logger",
    "dep:env_filter"
]

rp2350 = [
    "dep:embassy-rp",
    "dep:cyw43-pio",
    "dep:cortex-m-rt",
    "embassy-rp/rt",
    "embassy-rp/time-driver",
    "embassy-rp/critical-section-impl",
    #"embassy-rp/executor-thread",           # <-- Let the HAL define the hardware executor
    #"embassy-rp/executor-interrupt",        # <-- Add if you require high-priority interrupt task pools
    "embassy-executor/platform-cortex-m",   # <-- Explicitly satisfies the executor's platform check
    "embassy-executor/executor-thread",
    "motor-mixers/rp2350",
]

rp235xa =[
    "embassy-rp/rp235xa",
]

rp235xb =[
    "embassy-rp/rp235xb",
]

stm32 = [
    "dep:embassy-stm32",
    "dep:cortex-m-rt",
    "embassy-stm32/rt",
    "embassy-stm32/time-driver-tim2",
    "embassy-stm32/executor-thread",
    "embassy-stm32/executor-interrupt",
    "embassy-executor/platform-cortex-m",   # <-- Explicitly satisfies the executor's platform check
    "embassy-executor/executor-thread",
    "embassy-executor/executor-interrupt",
    "motor-mixers/stm32",
]

stm32f405 = [
    "embassy-stm32/stm32f405rg",
]

esp32 =[]

[dependencies]
# Core Embassy executor and concurrency primitives
embassy-executor = { version = "0.10.0", default-features = false }
embassy-futures = { version = "0.1.2", default-features = false }
embassy-time = { version = "0.5.1", default-features = false }
embassy-sync = { version = "0.8.0", default-features = false }
embedded-hal-async = { version = "1.0.0", default-features = false }
embassy-embedded-hal = "0.6.0"
embedded-io-async = "0.7.0"
static_cell = "2.1.1"
critical-section = { version = "1.2.0" }
# Hardware-specific Embassy HAL
cortex-m-rt = { version = "0.7.5", optional = true }
embedded-hal = { version = "1.0" }
embedded-hal-bus = { version = "0.3.0", features = ["async"] }
embedded-sdmmc = { version = "0.10.0", default-features = false, features = ["log"], optional = true }
# Raspberry Pi Pico specific
embassy-rp = { version = "0.10.0", default-features = false, optional = true }
# stm32f4 specific
embassy-stm32 = { version = "0.6.0", default-features = false, optional = true }
strum = { version = "0.28.0", default-features = false, features = ["derive"] }
cfg-if = "1.0.4"
derive_more = { version = "2.1.1", default-features = false, features = ["display"] }
num-traits = { version = "0.2.19", default-features = false }
libm = { version = "0.2.16", optional = true }

serde = { version = "1.0.228", default-features = false, features = ["derive"], optional = true }
postcard = { version = "1.1.3", default-features = false, features = ["embedded-io"], optional = true }
sequential-storage = { version = "8.0.1", default-features = false, features = ["postcard"] }
embedded-storage-async = { version = "0.4.1", default-features = false }
# In-memory storage simulator
embedded-storage-file = { version = "0.2.0", default-features = false, optional = true }

#simple-bitset = "0.1.5"
simple-bitset = { git = "https://github.com/martinbudden/crate-simple-bitset" }
#simple-bitset = { path = "../simple-bitset" }
stream-buf = "0.1.2"
#stream-buf = { git = "https://github.com/martinbudden/crate-stream-buf" }
#vqm = { version = "0.1.14" }
vqm = { git = "https://github.com/martinbudden/crate-vector-quaternion-matrix" }
#vqm = { path = "../vqm" }
#signal-filters = "0.1.10"
signal-filters = { git = "https://github.com/martinbudden/crate-signal-filters" }
#signal-filters = { path = "../signal-filters" }
#pidsk-controller = "0.1.8"
pidsk-controller = { git = "https://github.com/martinbudden/crate-pid-controller" }
#pidsk-controller = { path = "../pidsk-controller" }
#sensor-fusion = "0.1.9"
sensor-fusion = { git = "https://github.com/martinbudden/crate-sensor-fusion" }
#sensor-fusion = { path = "../sensor-fusion" }
#blackbox-logger = { version = "0.1.9", default-features = false, optional = true }
#blackbox-logger = { git = "https://github.com/martinbudden/crate-blackbox-logger", default-features = false, optional = true }
blackbox-logger = { path = "../blackbox-logger", default-features = false, optional = true }

#motor-mixers = { version = "0.1.5", default-features = false }
#motor-mixers = { git = "https://github.com/martinbudden/crate-motor-mixers", default-features = false }
motor-mixers = { path = "../motor-mixers", default-features = false }
#radio-controllers = { version = "0.1.6", default-features = false }
#radio-controllers = { git = "https://github.com/martinbudden/crate-radio-controllers", default-features = false}
radio-controllers = { path = "../radio-controllers", default-features = false }
#imu-sensors = { version = "0.1.3", default-features = false }
#imu-sensors = { git = "https://github.com/martinbudden/crate-imu-sensors", default-features = false }
imu-sensors = { path = "../imu-sensors", default-features = false }

paste = { version = "1.0.15", default-features = false }

tinyrand = { version = "0.5.0" }
log = { version = "0.4.33", default-features = false }
env_logger = { version ="0.11.10", default-features = false, optional = true}
env_filter = { version = "2.0.0", default-features = false, optional = true }
rtt-target = { version = "0.6.2", optional = true }
cyw43-pio = { version = "0.10.0", optional = true }


[dev-dependencies]
approx = { version = "0.5.1", default-features = false }


# see https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.dev]
opt-level = 0
debug = "line-tables-only"
# split-debuginfo = '...'  # Platform-specific.
strip = "none"
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[profile.dev.package."*"]
debug = false

[profile.debugging]
inherits = "dev"
debug = true

[profile.release]
opt-level = 3
debug = false
# split-debuginfo = '...'  # Platform-specific.
strip = "none"
debug-assertions = false
overflow-checks = false
lto = false
panic = 'abort'
incremental = false
codegen-units = 16
rpath = false

[profile.release-lto]
inherits = "release"
lto = true
codegen-units = 1    # Allows deeper optimizations across the entire binary
